# Generated by Django 4.1.7 on 2024-11-06 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proagua_api.models.solicitacao
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('campus', models.CharField(choices=[('LE', 'Leste'), ('OE', 'Oeste')], default=('LE', 'Leste'), max_length=20, verbose_name='campus')),
                ('cronograma', models.PositiveIntegerField(verbose_name='cronograma')),
                ('informacoes_gerais', models.TextField(blank=True, max_length=500, null=True, verbose_name='informações gerais')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('src', models.ImageField(upload_to='media/images')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temperatura', models.FloatField(blank=True, default=9.5, null=True, verbose_name='temperatura mínima')),
                ('max_temperatura', models.FloatField(blank=True, default=10.5, null=True, verbose_name='temperatura máxima')),
                ('min_cloro_residual_livre', models.FloatField(blank=True, default=0.2, null=True, verbose_name='cloro residual livre mínimo')),
                ('max_cloro_residual_livre', models.FloatField(blank=True, default=5.0, null=True, verbose_name='cloro residual livre máximo')),
                ('min_turbidez', models.FloatField(blank=True, default=None, null=True, verbose_name='turbidez mínima')),
                ('max_turbidez', models.FloatField(blank=True, default=5.0, null=True, verbose_name='turbidez máxima')),
                ('coliformes_totais', models.BooleanField(default=False, verbose_name='coliformes totais')),
                ('escherichia', models.BooleanField(default=False, verbose_name='escherichia coli')),
            ],
        ),
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(choices=[(0, 'Bebedouro'), (1, 'Torneira'), (2, 'Reservatório predial superior'), (3, 'Reservatório predial inferior'), (4, 'Reservatório de distribuição superior'), (5, 'Reservatório de distribuição inferior'), (6, 'CAERN')], default=(1, 'Bebedouro'), verbose_name='tipo')),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='localizacao')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('tombo', models.CharField(blank=True, max_length=40, null=True, verbose_name='tombo')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='quantidade')),
                ('capacidade', models.FloatField(blank=True, null=True, verbose_name='capacidade em (L)')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='material')),
                ('fonte_informacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='fonte de informação')),
                ('amontante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponto_amontante', to='proagua_api.pontocoleta', verbose_name='ponto amontante')),
                ('edificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PontoColeta', to='proagua_api.edificacao', verbose_name='código da edificação')),
                ('imagens', models.ManyToManyField(blank=True, to='proagua_api.image')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data da solicitação')),
                ('objetivo', models.TextField(blank=True, max_length=1250, null=True, verbose_name='objetivo da solicitação')),
                ('justificativa', models.TextField(blank=True, max_length=1250, null=True, verbose_name='justificativa da solicitação')),
                ('tipo', models.CharField(choices=[('Limpeza de reservatório', 'Limpeza de reservatório'), ('Instalação de ponto de coleta', 'Instalação de ponto de coleta'), ('Conserto de reservatório', 'Conserto de reservatório')], default='Limpeza de reservatório', max_length=50, verbose_name='tipo de solicitação')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], default=proagua_api.models.solicitacao.Status['PENDENTE'], max_length=50, verbose_name='status')),
                ('imagens', models.ManyToManyField(to='proagua_api.image')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Solicitacao', to='proagua_api.pontocoleta', verbose_name='ponto de coleta')),
            ],
        ),
        migrations.CreateModel(
            name='SequenciaColetas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amostragem', models.PositiveIntegerField(verbose_name='amostragem')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proagua_api.pontocoleta', verbose_name='ponto')),
            ],
            options={
                'unique_together': {('amostragem', 'ponto')},
            },
        ),
        migrations.AddField(
            model_name='edificacao',
            name='imagens',
            field=models.ManyToManyField(to='proagua_api.image'),
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperatura', models.FloatField(verbose_name='temperatura')),
                ('cloro_residual_livre', models.FloatField(verbose_name='cloro residual livre')),
                ('turbidez', models.FloatField(verbose_name='turbidez')),
                ('coliformes_totais', models.BooleanField(verbose_name='coliformes totais')),
                ('escherichia', models.BooleanField(verbose_name='escherichia coli')),
                ('cor', models.FloatField(verbose_name='cor')),
                ('data', models.DateTimeField(verbose_name='data da coleta')),
                ('ordem', models.CharField(choices=[('C', 'Coleta'), ('R', 'Recoleta')], default=('C', 'Coleta'), max_length=1)),
                ('status', models.BooleanField(default=None, null=True, verbose_name='status')),
                ('status_message', models.CharField(default=None, max_length=200, null=True, verbose_name='status message')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='proagua_api.pontocoleta', verbose_name='Ponto de Coleta')),
                ('responsavel', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='responsaveis')),
                ('sequencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='proagua_api.sequenciacoletas', verbose_name='sequência de Coletas')),
            ],
        ),
    ]
